app/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from extensions import db
from mixin import CRUDMixin
import config as CFG

from datetime import datetime
import os
import os.path as op

from werkzeug.security import (
    generate_password_hash,
    check_password_hash
)
# from sqlalchemy.event import listens_for
from sqlalchemy.ext.hybrid import hybrid_property
from flask import url_for


class Users(db.Model, CRUDMixin):
    login = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(80))

    def __init__(self, login, password):
        self.login = login
        self.set_password(password)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    # Flask-Login integration
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    # Required for administrative interface
    def __unicode__(self):
        return self.login


class Categories(db.Model, CRUDMixin):

    name = db.Column(db.String(256))

    def __unicode__(self):
        return self.name


class Events(db.Model, CRUDMixin):
    name = db.Column(db.String(256))
    tstamp = db.Column(db.DateTime,
                       default=datetime.utcnow().replace(second=0, microsecond=0))
    place = db.Column(db.String(256))
    city = db.Column(db.String(256))
    price_real = db.Column(db.Numeric(12, 2))
    price_discount = db.Column(db.Numeric(12, 2))
    descr = db.Column(db.UnicodeText)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    lat = db.Column(db.Numeric(12, 6))
    lng = db.Column(db.Numeric(12, 6))
    org_email = db.Column(db.String(256))
    availible_tickets = db.Column(db.Integer)
    bought_tickets = db.Column(db.Integer, default=0)

    category = db.relationship('Categories')

    def __unicode__(self):
        return self.name

    def get_img_url(self, img_name):
        return url_for(
            'static',
            filename=op.join('img', self.img_folder, img_name)
        )

    @property
    def img_folder(self):
        return "event_{0}_{1}".format(self.id, self.name)

    @hybrid_property
    def images(self):
        abs_folder = op.join(CFG.IMG_ROOT, self.img_folder)
        return sorted([self.get_img_url(f) for f in os.listdir(abs_folder)])

    @hybrid_property
    def img_url(self):
        return self.images[0] if self.images else None


class Payments(db.Model, CRUDMixin):

    hotel_name = db.Column(db.String(256))
    email = db.Column(db.String(256))
    amount = db.Column(db.Numeric(12, 2))
    name = db.Column(db.String(256))
    customer_id = db.Column(db.String(256))
    charge_id = db.Column(db.String(256))
    event_id = db.Column(db.Integer, db.ForeignKey('events.id'))
    status = db.Column(db.Boolean())
    error = db.Column(db.String(256))
    tstamp = db.Column(db.DateTime, default=datetime.utcnow())

    def __unicode__(self):
        return self.name

app/forms.py
from wtforms import (
    TextAreaField,
    FileField,
    form,
    fields,
    validators
)

from models import Users

class LoginForm(form.Form):
    login = fields.TextField(validators=[validators.required()])
    password = fields.PasswordField(validators=[validators.required()])

    def validate_login(self, field):
        user = self.get_user()

        if user is None:
            raise validators.ValidationError('Invalid user')

        if not user.check_password(self.password.data):
            raise validators.ValidationError('Invalid password')

    def get_user(self):
        return Users.query.filter_by(login=self.login.data).first()

app/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from utils import print_obj
from flask import Flask, render_template
# from flask.ext.restless import APIManager, ProcessingException
from extensions import db, admin, login, mail
from views import common
from api import api
from util_views import dev


app = Flask(__name__, template_folder='../templates',
            static_folder='../static', static_url_path ='')
app.config.from_object('config')

#login init
login.init_app(app)

# init db
db.app = app
db.init_app(app)

# init administration page
admin.init_app(app)
from admin import admin

#init mail
mail.init_app(app)

# register blueprint
app.register_blueprint(common)
app.register_blueprint(api, url_prefix='/api')
app.register_blueprint(dev, url_prefix='/dev')

app/auth.py
from models import Users
from forms import LoginForm
from extensions import login as login_manager

from flask import redirect, url_for, request
from flask.ext import login
from flask.ext.admin import AdminIndexView, expose, helpers


@login_manager.user_loader
def load_user(user_id):
    return Users.get(user_id)


class MyAdminIndexView(AdminIndexView):

    @expose('/')
    def index(self):
        if not login.current_user.is_authenticated():
            return redirect(url_for('.login_view'))
        return super(MyAdminIndexView, self).index()

    @expose('/login/', methods=('GET', 'POST'))
    def login_view(self):
        # handle user login
        form = LoginForm(request.form)
        if helpers.validate_form_on_submit(form):
            user = form.get_user()
            login.login_user(user)

        if login.current_user.is_authenticated():
            return redirect(url_for('.index'))
        link = '<p>Don\'t have an account? Go out</p>'
        self._template_args['form'] = form
        self._template_args['link'] = link
        return super(MyAdminIndexView, self).index()

    @expose('/logout/')
    def logout_view(self):
        login.logout_user()
        return redirect(url_for('.index'))

app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path as op
import csv

from utils import print_obj, as_dict_many
from extensions import mail
import config as CFG
from models import Payments

from flask import Blueprint, request, render_template, Response, redirect
from flask.ext.mail import Message


common = Blueprint('common_page', 'common_page')


@common.route('/')
def api():
    return "Blueprint works"


@common.route('/about')
def about():
    return render_template("about.html")


@common.route('/send_email', methods=["POST"])
def send_email():
    email_form = request.form
    if email_form:
        msg = Message(
            "Hello",
            sender="Contact Usher",
            recipients=CFG.ADMIN_EMAIL,
            body=email_form["email_text"]
        )
    mail.send(msg)
    return 'ok'


@common.route('/send_ticket', methods=["POST"])
def send_ticket():
    email_form = request.form
    print_obj(request)
    if email_form:
        mails = CFG.ADMIN_EMAIL + list(email_form["email_text"])
        msg = Message(
            "Hello",
            sender="Contact Usher",
            recipients=mails,
            body=email_form["email_text"]
        )
    mail.send(msg)
    return 'ok'


@common.route('/export_payments')
def export_payments():
    payments = as_dict_many(Payments.query.all())
    with open(op.join(CFG.CSV_ROOT, 'payments.csv'), 'wb') as f:
        w = csv.DictWriter(f, payments[0].keys())
        w.writeheader()
        [w.writerow(row) for row in payments]
    return redirect('/admin/exportadmin/')

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- StyleSheet -->
    <link rel="stylesheet" href="/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/bootstrap-responsive.css" />
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
</head>
<body>
    <div><h1 align="center">API Docs</h1></div>
    <div class="container">
        <div class="row">
            <h3>Events</h3>
            <table class="table table-bordered">
                <tr>
                    <td>URL</td>
                    <td><pre>/api/events</pre></td>
                </tr>
                <th colspan="2">GET</th>
                <tr>
                    <td>Parameters</td>
                    <td>
                        <ul>
                        <li>date_from</li>
                            <ul>
                                <li><pre class="prettyprint">type:datetime ("2014-05-07T09:33:57")</pre></li>
                                <li><pre class="prettyprint">example_url: "/api/events?date_from=2014-05-07"</pre></li>
                            </ul>
                        <li>date_to</li>
                            <ul>
                                <li><pre class="prettyprint">type:datetime ("2014-05-07T09:33:57")</pre></li>
                                <li><pre class="prettyprint">example_url: "/api/events?date_to=2014-07-07"</pre></li>
                            </ul>
                        <li>category</li>
                            <ul>
                                <li><pre class="prettyprint">type:text</pre></li>
                                <li><pre class="prettyprint">example_url: "/api/events?category=Music"</pre></li>
                            </ul>
                        <li>limit</li>
                            <ul>
                                <li><pre class="prettyprint">type:int</pre></li>
                                <li><pre class="prettyprint">example_url: "/api/events?limit=3"</pre></li>
                            </ul>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>200 example answer</td>
                    <td><pre class="prettyprint">
[
   {
      "category":"music",
      "city":"Dnepropetrovsk",
      "name":"Great_event",
      "descr":"sdafsdfs",
      "price_real":"34.00",
      "tstamp":"2014-06-11T16:27:00",
      "lat":"48.454709",
      "place":"Uralska St 30",
      "images":[
         "/img/event_5_Great_event/IMG_19052014_182430.png",
         "/img/event_5_Great_event/268708910.jpg"
      ],
      "lng":"34.998828",
      "id":5,
      "price_discount":"23.00"
   },
   {
      "category":"music",
      "city":"New York",
      "name":"Party time",
      "descr":"bla",
      "price_real":"20.00",
      "tstamp":"2014-05-07T23:50:00",
      "lat":"40.738481",
      "place":"National Theatre",
      "images":[

      ],
      "lng":"-73.988719",
      "id":1,
      "price_discount":"10.00"
   }
]
                    </pre></td>
                </tr>
            </table>
        </div>
    </div>
</body>
<footer>
</footer>
</html>

templates/events_create.html
{% extends 'admin/model/create.html' %}
 
{% block tail %}
    {{ super() }}
    <script src="/js/events.js"></script>
{% endblock %}

templates/events_edit.html
{% extends 'admin/model/edit.html' %}
 
{% block tail %}
    {{ super() }}
    <script src="/js/events.js"></script>
{% endblock %}

templates/images_list.html
{% extends 'admin/file/list.html' %}
 
{% block toolbar %}
    {{ super() }}
    <div class="btn-group">
        <a href="{{ url_for('common_page.export_payments') }}" class="btn btn-primary">
            Export payments
        </a>
    </div> 
{% endblock %}

templates/images_upload.html
{% extends 'admin/file/form.html' %}
 
{% block tail %}
    {{ super() }}
    <script src="/js/upload_image.js"></script>
{% endblock %}

templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated() %}
<div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('admin.logout_view') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}